Fix background Preview2D not showing a preview
Since commit 29707794bb78a411e0850e4c558da0e69d10f99c, enabling the
Preview2D BackgroundPreview shows a white color instead of the preview,
and prints the following errors in the console:

  ERROR: (Node not found: "ContextMenu" (relative to "/root/MainWindow/VBoxContainer/Layout/SplitRight/ProjectsPanel/BackgroundPreviews/Preview2D").)
     at: get_node (scene/main/node.cpp:1325)
  ERROR: (Node not found: "ContextMenu" (relative to "/root/MainWindow/VBoxContainer/Layout/SplitRight/ProjectsPanel/BackgroundPreviews/Preview2D").)
     at: get_node (scene/main/node.cpp:1325)
  SCRIPT ERROR: Attempt to call function 'get_item_index' in base 'null instance' on a null instance.
     at: set_generator (res://material_maker/panels/preview_2d/preview_2d.gd:78)

This commit guards the ContextMenu update with a null check.