Fix invalid swizzle in some paint shaders
Using components from the `xyzw` and `rgba` sets in a single swizzle
operation was causing a shader compilation error when painting:

    error: invalid swizzle / mask `za'